# 実行前にimportブロックを用意しておくこと。
name: Generate config out
run-name: terraform plan -generate-config-out (${{inputs.working_dir}})
on:
  workflow_dispatch:
    inputs:
      working_dir:
        description: working directory
        required: true
      file:
        description: file name
        required: true
      branch:
        description: branch name
        required: true
permissions:
  id-token: write # For OIDC
  contents: read # For checkout a private repository
  pull-requests: write
env:
  TFACTION_WORKING_DIR: ${{github.event.inputs.working_dir}}
  TFACTION_JOB_TYPE: terraform
  FILE: ${{inputs.file}}
  BRANCH: ${{inputs.branch}}
jobs:
  import:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: ${{ split(inputs.working_dir, '/')[1] }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{inputs.branch}}
          persist-credentials: false

      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.53.3
          working_directory: ${{env.TFACTION_WORKING_DIR}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app_id: ${{secrets.TFACTION_GITHUB_APP_ID}}
          private_key: ${{secrets.TFACTION_GITHUB_PRIVATE_KEY}}

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN_PLAN }}
          aws-region: ap-northeast-1

      - uses: suzuki-shunsuke/tfaction/setup@c7f4e11bb3b673f40c3894b7612669e149d7b452 # v1.19.2
        id: setup
        with:
          github_token: ${{steps.generate_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction/generate-config-out@c7f4e11bb3b673f40c3894b7612669e149d7b452 # v1.19.2
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
        with:
          github_token: ${{steps.generate_token.outputs.token}}
          branch: ${{inputs.branch}}
          file: ${{inputs.file}}
