name: terraform-plan

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feature/setup_tfaction # temp

      - name: Install tools
        uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.3

      - name: Get changed directories
        uses: suzuki-shunsuke/tfaction/list-targets@v1.17.0
        id: list-targets

  plan:
    name: "terraform plan (${{ matrix.target.target }})"
    runs-on: ubuntu-latest
    needs: setup
    if: join(fromJSON(needs.setup.outputs.targets), '') != ''
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{matrix.target.working_directory}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feature/setup_tfaction # temp

      - name: Install tools
        uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.3

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private-key: ${{ secrets.TFACTION_GITHUB_PRIVATE_KEY }}

      - name: Set up
        uses: suzuki-shunsuke/tfaction/setup@v1.17.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

      - name: Plan
        uses: suzuki-shunsuke/tfaction/plan@v1.17.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
