name: terraform-plan

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: feature/setup_tfaction # temp

      - uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.3

      - uses: suzuki-shunsuke/tfaction/list-targets@v1.17.0
        id: list-targets

  plan:
    name: "terraform plan (${{ matrix.target.target }})"
    runs-on: ubuntu-latest
    needs: setup
    if: join(fromJSON(needs.setup.outputs.targets), '') != ''
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{matrix.target.working_directory}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: feature/setup_tfaction # temp

      - name: Check files
        run: ls -la

      - uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.3

      - id: github_app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private-key: ${{ secrets.TFACTION_GITHUB_PRIVATE_KEY }}

      - uses: suzuki-shunsuke/tfaction/setup@v1.17.0
        with:
          github_app_token: ${{ steps.github_app_token.outputs.token }}
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction/plan@v1.17.0
        with:
          github_app_token: ${{ steps.github_app_token.outputs.token }}
