name: Terraform test
on:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  TRIVY_CONFIG: ${{ github.workspace }}/trivy.yaml
  TRIVY_IGNOREFILE: ${{ github.workspace }}/.trivyignore.yaml
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
      modules: ${{ steps.list-targets.outputs.modules }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install tools
        uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.53.3

      - name: Get changed directories
        uses: suzuki-shunsuke/tfaction/list-targets@fe01abc967d9c7a9889abbb8502e2947a1dfece3 # v1.17.0
        id: list-targets

  envs-test:
    name: "terraform plan (${{ matrix.target.target }})"
    runs-on: ubuntu-latest
    needs: setup
    if: join(fromJSON(needs.setup.outputs.targets), '') != ''
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    environment: ${{ matrix.target.target }}
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{matrix.target.working_directory}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
      TFLINT_CONFIG_FILE: ${{ github.workspace }}/environments/.tflint.hcl
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install tools
        uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.53.3

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private-key: ${{ secrets.TFACTION_GITHUB_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN_PLAN }}
          aws-region: ap-northeast-1

      - name: Set up
        uses: suzuki-shunsuke/tfaction/setup@fe01abc967d9c7a9889abbb8502e2947a1dfece3 # v1.17.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

      - name: Test
        uses: suzuki-shunsuke/tfaction/test@fe01abc967d9c7a9889abbb8502e2947a1dfece3 # v1.17.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

  modules-test:
    name: Test module (${{ matrix.target }})
    runs-on: ubuntu-latest
    needs: setup
    if: join(fromJSON(needs.setup.outputs.modules), '') != ''
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.modules) }}
    env:
      TFACTION_TARGET: ${{ matrix.target }}
      TFLINT_CONFIG_FILE: ${{ github.workspace }}/modules/.tflint.hcl
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install tools
        uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.53.3

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private-key: ${{ secrets.TFACTION_GITHUB_PRIVATE_KEY }}

      - name: Test
        uses: suzuki-shunsuke/tfaction/test-module@fe01abc967d9c7a9889abbb8502e2947a1dfece3 # v1.17.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
