name: Terraform test
on:
  pull_request:
    branches: main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  TRIVY_CONFIG: ${{ github.workspace }}/trivy.yaml
  TRIVY_IGNOREFILE: ${{ github.workspace }}/.trivyignore.yaml
  TFLINT_CONFIG_FILE: ${{ github.workspace }}/modules/.tflint.hcl
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
      modules: ${{ steps.list-targets.outputs.modules }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.3

      - name: Get changed directories
        uses: suzuki-shunsuke/tfaction/list-targets@v1.17.0
        id: list-targets

  envs-test:
    name: "terraform plan (${{ matrix.target.target }})"
    runs-on: ubuntu-latest
    needs: setup
    if: join(fromJSON(needs.setup.outputs.targets), '') != ''
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{matrix.target.working_directory}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN_PLAN }}
          aws-region: ap-northeast-1

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private-key: ${{ secrets.TFACTION_GITHUB_PRIVATE_KEY }}

      - name: Set up
        uses: suzuki-shunsuke/tfaction/setup@v1.17.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

      - name: Test
        uses: suzuki-shunsuke/tfaction/test@v1.17.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}

  modules-test:
    name: Test module (${{ matrix.target }})
    runs-on: ubuntu-latest
    needs: setup
    if: join(fromJSON(needs.setup.outputs.modules), '') != ''
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.modules) }}
    env:
      TFACTION_TARGET: ${{ matrix.target }}
      TFLINT_CONFIG_FILE: ${{ github.workspace }}/modules/.tflint.hcl
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.3

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TFACTION_GITHUB_APP_ID }}
          private-key: ${{ secrets.TFACTION_GITHUB_PRIVATE_KEY }}

      - name: Test(module)
        uses: suzuki-shunsuke/tfaction/test-module@v1.17.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
